jrk_settings:
  product: JRK_PRODUCT_UMC05A_30V
  input_mode: JRK_INPUT_MODE_SERIAL
  input_error_minimum: 0
  input_error_maximum: 4095
  input_minimum: 0
  input_maximum: 4095
  input_neutral_minimum: 2048
  input_neutral_maximum: 2048
  output_minimum: 0
  output_neutral: 2048
  output_maximum: 4095
  input_invert: false
  input_scaling_degree: JRK_SCALING_DEGREE_LINEAR
  input_detect_disconnect: false
  input_analog_samples_exponent: 7
  feedback_mode: JRK_FEEDBACK_MODE_NONE
  feedback_error_minimum: 0
  feedback_error_maximum: 4095
  feedback_minimum: 0
  feedback_maximum: 4095
  feedback_invert: false
  feedback_detect_disconnect: false
  feedback_dead_zone: 0
  feedback_analog_samples_exponent: 7
  feedback_wraparound: false
  serial_mode: JRK_SERIAL_MODE_USB_DUAL_PORT
  serial_baud_rate: 9600
  serial_timeout: 0
  serial_device_number: 11
  never_sleep: false
  serial_enable_crc: false
  serial_enable_14bit_device_number: false
  serial_disable_compact_protocol: false
  proportional_multiplier: 0
  proportional_exponent: 0
  integral_multiplier: 0
  integral_exponent: 0
  derivative_multiplier: 0
  derivative_exponent: 0
  pid_period: 10
  integral_divider_exponent: 0
  integral_limit: 1000
  reset_integral: false
  pwm_frequency: 20
  current_samples_exponent: 7
  hard_overcurrent_threshold: 1
  current_offset_calibration: 0
  current_scale_calibration: 0
  motor_invert: false
  max_duty_cycle_while_feedback_out_of_range: 600
  max_acceleration_forward: 600
  max_acceleration_reverse: 600
  max_deceleration_forward: 600
  max_deceleration_reverse: 600
  max_duty_cycle_forward: 600
  max_duty_cycle_reverse: 600
  encoded_hard_current_limit_forward: 86
  encoded_hard_current_limit_reverse: 86
  brake_duration_forward: 0
  brake_duration_reverse: 0
  soft_current_limit_forward: 0
  soft_current_limit_reverse: 0
  coast_when_off: false
  error_enable: 0
  error_latch: 0
  error_hard: 0
  vin_calibration: 0
  disable_i2c_pullups: false
  analog_sda_pullup: false
  always_analog_sda: false
  always_analog_fba: false
  fbt_method: JRK_FBT_METHOD_PULSE_COUNTING
  fbt_timing_clock: JRK_FBT_TIMING_CLOCK_1_5
  fbt_timing_polarity: false
  fbt_timing_timeout: 100
  fbt_samples: 1
  fbt_divider_exponent: 0
